import AppKit
import ImageIO

struct ClipItem: Identifiable, Equatable, Codable {
    enum Content: Equatable, Codable {
        case text(String)
        /// Küçültülmüş PNG (≤ 640 px); tam boyutlu ekran görüntüleri bellekte tutulmaz.
        case image(Data)
        case files([URL])
    }

    var id = UUID()
    let content: Content
    let date: Date
    let sourceApp: String?
}

/// Pano geçmişi — **yoklamasız, olay güdümlü**.
///
/// NSPasteboard'un public bir değişiklik bildirimi yok. Sürekli `changeCount` yoklamak yerine
/// yalnızca panonun değişmiş olabileceği anlarda tek seferlik kontrol yapılır:
/// 1. Kullanıcı başka bir uygulamaya geçtiğinde (`NSWorkspace.didActivateApplicationNotification`).
/// 2. ⌘C / ⌘X basıldığında (Erişilebilirlik izni varsa). Her tuş vuruşunu dinlememek için yalnızca
///    `flagsChanged` izlenir; ⌘ basılıyken geçici bir `keyDown` izleyicisi kurulur, ⌘ bırakılınca kalkar.
/// 3. Ada genişlediğinde (kullanıcı geçmişe bakmak üzere).
/// Ödünleşim: menüden fareyle "Kopyala" yapılıp aynı uygulamada kalınırsa öğe, bir sonraki uygulama
/// geçişinde veya ada açıldığında yakalanır.
///
/// Gizlilik:
/// - `org.nspasteboard.ConcealedType/TransientType` işaretli içerik (parola yöneticileri) kaydedilmez.
/// - macOS 15.4+ `NSPasteboard.accessBehavior`: kullanıcı panoya erişimi "Asla" yaptıysa izleme durur.
///   Apple'ın pano gizlilik modelinde `changeCount` okumak uyarı tetiklemez, içerik okumak tetikler
///   (kullanıcı "Her zaman izin ver" diyene kadar).
@MainActor
@Observable
final class ClipboardHistory {
    private(set) var items: [ClipItem] = []
    private(set) var isBlockedBySystem = false
    private(set) var isRunning = false
    var limit = 40

    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var activationObserver: NSObjectProtocol?
    @ObservationIgnored private var modifierMonitor: Any?
    @ObservationIgnored private var shortcutMonitor: Any?
    @ObservationIgnored private var pendingCheck: Task<Void, Never>?
    /// Uygulama geçişinde kopyalama önceki uygulamada yapılmıştır; kaynağı doğru atamak için tutulur.
    @ObservationIgnored private var previousFrontmostName = NSWorkspace.shared.frontmostApplication?.localizedName
    @ObservationIgnored private let storeURL: URL

    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init(storeURL: URL = AppPaths.support.appendingPathComponent("clipboard.json")) {
        self.storeURL = storeURL
        load()
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = NSPasteboard.general.changeCount
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
        ) { [weak self] note in
            let activated = (note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication)?.localizedName
            MainActor.assumeIsolated {
                guard let self else { return }
                self.checkNow(source: self.previousFrontmostName)
                self.previousFrontmostName = activated
            }
        }
        setShortcutMonitoring(AXIsProcessTrusted())
    }

    func stop() {
        guard isRunning else { return }
        isRunning = false
        if let activationObserver { NSWorkspace.shared.notificationCenter.removeObserver(activationObserver) }
        activationObserver = nil
        setShortcutMonitoring(false)
        pendingCheck?.cancel()
    }

    /// Ada açıldığında veya pano sekmesi gösterildiğinde çağrılır.
    func refresh() {
        guard isRunning else { return }
        checkNow()
    }

    /// Erişilebilirlik izni verildiğinde/geri alındığında koordinatör tarafından çağrılır.
    func setShortcutMonitoring(_ enabled: Bool) {
        if enabled, isRunning, modifierMonitor == nil {
            modifierMonitor = NSEvent.addGlobalMonitorForEvents(matching: .flagsChanged) { [weak self] event in
                let commandDown = event.modifierFlags.contains(.command)
                MainActor.assumeIsolated { self?.commandKeyChanged(isDown: commandDown) }
            }
        } else if !enabled {
            if let modifierMonitor { NSEvent.removeMonitor(modifierMonitor) }
            modifierMonitor = nil
            commandKeyChanged(isDown: false)
        }
    }

    private func commandKeyChanged(isDown: Bool) {
        if isDown, shortcutMonitor == nil {
            shortcutMonitor = NSEvent.addGlobalMonitorForEvents(matching: .keyDown) { [weak self] event in
                let key = event.charactersIgnoringModifiers?.lowercased()
                guard key == "c" || key == "x" else { return }
                MainActor.assumeIsolated { self?.scheduleCheckAfterCopy() }
            }
        } else if !isDown, let shortcutMonitor {
            NSEvent.removeMonitor(shortcutMonitor)
            self.shortcutMonitor = nil
        }
    }

    /// Uygulama panoya kısayoldan hemen sonra yazar; kısa, tek seferlik iki kontrol yeterlidir.
    private func scheduleCheckAfterCopy() {
        pendingCheck?.cancel()
        pendingCheck = Task { [weak self] in
            for delay in [0.15, 0.6] {
                try? await Task.sleep(for: .seconds(delay))
                guard !Task.isCancelled else { return }
                if self?.checkNow() == true { return }
            }
        }
    }

    func copy(_ item: ClipItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.content {
        case .text(let text): pasteboard.setString(text, forType: .string)
        case .image(let data): pasteboard.setData(data, forType: .png)
        case .files(let urls): pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
        lastChangeCount = pasteboard.changeCount // kendi yazdığımızı yeni öğe sayma
        promote(item)
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func clear() {
        items.removeAll()
        save()
    }

    // MARK: - Private

    /// `true` dönerse yeni bir değişiklik bulundu.
    @discardableResult
    private func checkNow(source: @autoclosure () -> String? = NSWorkspace.shared.frontmostApplication?.localizedName) -> Bool {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return false }
        lastChangeCount = pasteboard.changeCount
        // Opening an unchanged history must not fetch LaunchServices application metadata.
        capture(from: pasteboard, source: source())
        return true
    }

    private func capture(from pasteboard: NSPasteboard, source: String?) {
        if #available(macOS 15.4, *) {
            isBlockedBySystem = pasteboard.accessBehavior == .alwaysDeny
            if isBlockedBySystem { return }
        }
        guard let types = pasteboard.types, Self.ignoredTypes.isDisjoint(with: types) else { return }

        let content: ClipItem.Content?
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            content = .files(urls)
        } else if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            content = .text(text)
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
                  let thumbnail = Self.downsampledPNG(from: data, maxPixel: 640) {
            content = .image(thumbnail)
        } else {
            content = nil
        }
        guard let content else { return }
        promote(ClipItem(content: content, date: Date(), sourceApp: source))
    }

    private func promote(_ item: ClipItem) {
        // Recopying the current entry changes neither ordering nor visible content. Keep the
        // existing row (and its copy confirmation) instead of rebuilding it and rewriting disk.
        if let first = items.first, first.content == item.content, first.sourceApp == item.sourceApp,
           items.count <= limit { return }
        var updated = items
        let existingID = updated.first { $0.content == item.content }?.id
        updated.removeAll { $0.content == item.content }
        updated.insert(ClipItem(id: existingID ?? item.id, content: item.content,
                                date: Date(), sourceApp: item.sourceApp), at: 0)
        if updated.count > limit { updated.removeLast(updated.count - limit) }
        items = updated
        save()
    }

    /// ImageIO ile belleğe tam görüntüyü açmadan küçük önizleme üretir.
    static func downsampledPNG(from data: Data, maxPixel: Int) -> Data? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixel,
            kCGImageSourceCreateThumbnailWithTransform: true,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        return NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])
    }

    /// Yalnızca metin ve dosya öğeleri kalıcıdır; görseller oturumla sınırlıdır.
    private func save() {
        let persistable = items.filter { if case .image = $0.content { false } else { true } }
        guard let data = try? JSONEncoder().encode(persistable) else { return }
        try? data.write(to: storeURL, options: .atomic)
    }

    private func load() {
        guard let data = try? Data(contentsOf: storeURL),
              let saved = try? JSONDecoder().decode([ClipItem].self, from: data) else { return }
        items = saved
    }
}
